export enum ReferralSource {
	Unknown = 0,
	Friend = 1,
	SocialMedia = 2,
	Facebook = 3,
	LinkedIn = 4,
	Instagram = 5,
	GoogleSearch = 6,
	Advertisement = 7,
	Website = 8,
	EmailCampaign = 9,
	Conference = 10,
	Partner = 11,
	Other = 12,
}
